College/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'College'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'student_registration/', views.student_registration, name='registration'),
    url(r'application/', views.application, name='application'),
    url(r'login/', views.user_login, name='user_login'),
    url(r'student_profile/',views.student_profile,name='student_profile'),
    url(r'staff_registration/', views.staff_registration, name='staff_registration'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

rolls/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'rolls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$',views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results$',views.results,name='results'),
    url(r'^(?P<question_id>[0-9]+)/votes$',views.vote,name='vote'),

    url('^image_upload/', views.hotel_image_view, name = 'image_upload'),
    url('^display/', views.display_hotel_images, name='display'),


    ]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rolls/',include('rolls.urls')),
    url(r'^College/',include('College.urls')),
]

College/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


department_choice = [
    ('mech', 'mechanical engineering'),
    ('cse', 'computers science engineering'),
    ('eee', 'electrical engineering'),
    ('ece', 'electronic engineering'),
]
gender_choice = [
    ('M', 'male'),
    ('F', 'female'),
    ('O', 'others'),
]


# class TimeStampedModel():
#
#
#     class Meta:
#         abstract = True


class Application(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    dob = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=5, choices=gender_choice)
    department = models.CharField(max_length=5, choices=department_choice)
    ssc_marklist = models.FileField(upload_to='document/')
    inter_marklist = models.FileField(upload_to='document/')
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return '{},{},{}'.format(self.name, self.email, self.is_verified)


class StudentRegistration(models.Model):
    name = models.OneToOneField(
        Application,
        on_delete=models.CASCADE)
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE)
    father_name = models.CharField(max_length=50)
    mother_name = models.CharField(max_length=50)
    profile_pic = models.ImageField(upload_to='image/')
    age = models.IntegerField(default=0)

    def __str__(self):
        return "{} {}".format(self.name, self.user.username)


class StaffRegistration(models.Model):
    name = models.CharField(max_length=50)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    father_name = models.CharField(max_length=50)
    mother_name = models.CharField(max_length=50)
    profile_pic = models.ImageField(upload_to='image/')
    department = models.CharField(max_length=5, choices=department_choice)
    age = models.IntegerField(default=0)
    salary = models.IntegerField(default=0)
    gender = models.CharField(max_length=5, choices=gender_choice)

    def __str__(self):
        return "{} {}".format(self.name, self.user.username)

College/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Application, StudentRegistration, User, StaffRegistration
from .student_registrationform import RegistrationForm, UserForm
from .applicationform import ApplicationForm
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from .staff_registartion import StaffRegistrationForm, StaffUserForm


def index(request):
    return render(request, 'College/index.html', )


def application(request):
    # import pdb;pdb.set_trace()
    if request.method == 'POST':
        Application.objects.create(
            name=request.POST['name'],
            gender=request.POST['gender'],
            email=request.POST['email'],
            dob=request.POST['dob'],
            department=request.POST['department'],
            ssc_marklist=request.FILES['ssc_marklist'],
            inter_marklist=request.FILES['inter_marklist'],

        )
        return HttpResponseRedirect(reverse('College:index'))
    return render(request, 'College/ApplicationForm.html', {})


def student_registration(request):
    if request.method == 'GET':
        form1 = UserForm()
        form2 = RegistrationForm()
        return render(request, 'College/RegistrationForm.html', {'form1': form1, 'form2': form2})
    form1 = UserForm(request.POST)
    form2 = RegistrationForm(request.POST, request.FILES)
    email = request.POST['email']
    studenta = Application.objects.filter(email=email, is_verified=True)
    studentb = Application.objects.get(email=email, is_verified=True)

    if studenta.exists() and form2.is_valid():
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = User.objects.create_user(username, email, password)

        StudentRegistration.objects.create(
            user=user,
            name=studentb,
            age=form2.data["age"],
            father_name=form2.data["father_name"],
            mother_name=form2.data["mother_name"],
            profile_pic=request.FILES.get("profile_pic")
        )
        return HttpResponseRedirect(reverse('College:index'))

    return render(request,
                  'College/RegistrationForm.html',
                  {'form1': form1, 'form2': form2})


def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, 'College/student_profile.html', {})

        else:
            return HttpResponse("user not found")

    else:
        return render(request, 'College/user_login.html', {})


def student_profile(request):
    student = StudentRegistration.objects.get(user__username=request.user)
    return render(request, 'College/student_profile.html', {'student': student})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('College:index'))


def staff_registration(request):
    if request.method == "POST":
        form1 = StaffUserForm(request.POST)
        form2 = StaffRegistrationForm(request.POST, request.FILES)
        # import ipdb
        # ipdb.set_trace()

        if form1.is_valid() and form2.is_valid():
            # import ipdb
            # ipdb.set_trace()
            username = request.POST['username']
            password = request.POST['password']
            email = request.POST['email']
            user = User.objects.create_user(username, email, password)
            StaffRegistration.objects.create(

                name=form2.data['name'],
                user=user,
                father_name=form2.data['father_name'],
                mother_name=form2.data['mother_name'],
                profile_pic=request.FILES.get("profile_pic"),
                department=form2.data['department'],
                age=form2.data['age'],
                salary=form2.data['salary'],
                gender=form2.data['gender'],
            )
            HttpResponse('success')
            # return HttpResponseRedirect(reverse('College:index'))
        else:
            HttpResponse('failed')

    else:
        form1 = StaffUserForm()
        form2 = StaffRegistrationForm()
        return render(request, 'College/staffregistration.html', {'form1': form1, 'form2': form2})

College/templates/College/ApplicationForm.html
<form class="" action="." method="post" enctype="multipart/form-data">
  {% csrf_token %}
  Name: <input type="text" name="name"><br><br>
  Gender: <select name="gender">
    <option value="M">Male</option>
    <option value="F">Female</option>
    <option value="O">Others</option>
  </select><br><br>
  Email : <input type="email" name="email"><br><br>
  Date of Birth : <input type="date" name="dob"><br><br>
  ssc_marklist: <input type="file" name="ssc_marklist"><br><br>
  inter_marklist: <input type="file" name="inter_marklist"><br><br>
  Department :<select name="department">
    <option value="CE">Civil Engineering</option>
    <option value="CSE">Computer Science Engineering</option>
    <option value="ECE">Electronics Communtication Engineering</option>
    <option value="EEE">Electrical Electronics Engineering</option>
    <option value="ME">Mechanical Engineering</option>
  </select>

  <input type="submit" value="submit" />
</form>

College/templates/College/RegistrationForm.html
<form action="." method="post" enctype="multipart/form-data">
   {% csrf_token %}
  {% for field in form1 %}
    {{ field.label_tag }} {{ field }}<br><br>
  {% endfor %}
  {% for field in form2 %}
    {{ field.label_tag }} {{ field }}
  {% endfor %}

  <button type="submit">submit</button>
</form>

College/templates/College/index.html
<ul>
<a href = "#"> Staff Registration </a> <br>
<a href = "{% url 'College:application'%}" > Student Application </a> <br>
<a href = "{% url 'College:registration' %}" > Student Registartion </a> <br>

    <a href = "{% url 'College:user_login' %}"> LOGIN</a><br>
</ul>

College/templates/College/staffregistration.html
<form action="." method="post" enctype="multipart/form-data">
   {% csrf_token %}
  {% for field in form1 %}
    {{ field.label_tag }} {{ field }}
  {% endfor %}


  {% csrf_token %}
  {% for field in form2 %}
    {{ field.label_tag }} {{ field }}
  {% endfor %}

  <button type="submit">submit</button>
</form>

College/templates/College/student_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<p>Name:{{stnd.name}}</p><br>
<img src="{{student.profilepic.url}}" ><br><br>
<p>Email:{{stnd.name.email}}</p><br>
<p>Date of Birth:{{stnd.name.dob}}</p>
<p>Gender:{{stnd.name.gender}}</p><br>
<p>Father Name:{{stnd.father}}</p><br>
<p>Mother Name:{{stnd.mother}}</p><br>
<a href="{{student.name.sccmemo.url}}">SSC Memo</a><br>
<a href="{{student.name.intermemo.url}}">Intermediate Memo</a><br>
<p>Department:{{student.name.department}}</p><br>

<a href = "{% url 'College:user_logout' %}">Logout</a>
</body>
</html>

College/templates/College/user_login.html
<form action="." method="POST">
{% csrf_token %}
    username : <input type="text" name="username">
    email    : <input type="email" name="email">
    password : <input type="password" name="password">

    <input type="submit" value="login" >
</form>